---
# Tomcat 9 â€” RHEL 9 / Rocky 9
tomcat_version: "9.0.102"
tomcat_mirror: "https://archive.apache.org/dist/tomcat/tomcat-9"
tomcat_install_dir: /opt/tomcat
tomcat_user: tomcat
tomcat_group: tomcat
tomcat_connector_port: 8080
# Optional: 8443 for HTTPS
tomcat_connector_redirect_port: 8443
